# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Erik Sorensen
tagline:          'Its good for you.'
description:      'A living chronicle of my projects in data science, and anything else I find fit to post.'
url:              http://squip.github.io

author:
  name:           'ESSORENSEN'
  url:            https://squip.github.io

paginate:         2

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/squip/squip.github.io

# Disqus
disqus:
  shortname:      essorensen

